# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabbarCustomerConfig' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry'
  pod 'HHRouter', '~> 0.1.8'

  target 'TabbarCustomerConfigTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabbarCustomerConfigUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
